name: CI

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ["2.6", "2.7", "3.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup database
        run: psql -c 'create database aaa_test;' -h localhost -U postgres
      - name: Run tests
        run: bundle exec rake
